config:
  time-zone: Europe/Moscow

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
#    url: jdbc:postgresql://postgres:5432/library
    username: library
    password: library
  flyway:
    schemas:
      - library

server:
  port: 8081

#debug: true